### ISSUE TITLE
Consider using A3C

### ISSUE THREAD

**Issue by iaroslav-ai** [dandxy89/rf_helicopter#4]
Maybe an idea for future development: there recently appeared a new algorithm called A3C, described in [this paper](http://arxiv.org/pdf/1602.01783v1.pdf), which at least on the tests in the paper improves over other algorithms (e.g. DQN). Would be really cool to have it implemented with Keras.

**Comment by dandxy89** [comment]
I'll look into it @iarlslav-ai
